name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Build job: Make executable from source.
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    # Add a step to install Doxygen
    - name: Install Doxygen
      run: |
        choco install doxygen.portable -y
        set PATH="/c/tools/doxygen:$PATH"
    # Add a step to generate documentation using Doxygen
    - name: Generate Documentation
      run: doxygen Doxyfile
      
    # Print versions.
    - name: print versions
      run: |
        gcc -v
        gcc --version
        make -v
        mingw32-make -v
    
    # Build with Makefile.
    - name: Run make.
      run: make all
    - name: Run tests (make check).
      run: make check
    - name: Run ? (make distcheck).
      run: make distcheck
  
  # Codecov job: Run CodeCov.
  codecov:
    if: ${{ always() }} # always run this job even if previous jobs failed.
    needs: build # run this job after "build" job has finished.
    runs-on: windows-latest
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
