name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC 8.3.0
      run: |
        choco install mingw --version=8.3.0
        echo "##[add-path]$($(Get-Command mingw).Source.Replace('\\bin\\mingw32-make.exe', ''))"
      shell: bash
    - name: make all
      run: make all
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
