name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Doxygen job: Extract documentation from source files.
  # TODO: Host it somewhere, e.g. Github Pages.
  documentation:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    # Assume doxygen is already installed.
    # Add a step to install Doxygen
    #- name: Install Doxygen
    #  run: |
    #    choco install doxygen.portable -y
    #    set PATH="/c/tools/doxygen:$PATH"
    # Add a step to generate documentation using Doxygen
    - name: Generate Documentation
      run: doxygen Doxyfile
      #run: doxygen -g
       
  # Build job: Make executable from source using Makefile.
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Chocolatey Installation
        run: choco --version
      - name: Install build tools and build
        shell: bash
        run: |
          choco install make
          make --version
          cd build-tools/strawberryperl/c/bin
          export PATH="$PWD:$PATH"
          echo "Updated PATH: $PATH"
          cd $GITHUB_WORKSPACE
          make all
          make check
          make distcheck

  # Perform unit tests to ensure game functionality works as it should.
  unit-tests:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Perform unit testing
        run: |
          make test
  
  # Coverage job: Upload coverage reports somewhere.
  coverage:
    if: ${{ always() }} # always run this job even if previous jobs failed.
    #needs: build # run this job after "build" job has finished.
    needs: [build, unit-tests]
    runs-on: windows-latest
    steps:
    #- name: Coveralls
    #  uses: coverallsapp/github-action@v2
    #  env:
    #    github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Codecov (faulty)
      #uses: codecov/codecov-action@v3
      uses: actions/checkout@v3
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/*.c.txt
    - run: |
        cmd

        dir
        ls
        cd COSC345-Game/
        dir
        ls
        
        cd coverage/
        ./codecov.exe -B main -f %files% -t "$token"
        ./codecov.exe -B main -f coverage/*.c.txt -t ""
        
    
