name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  # Doxygen job: Extract documentation from source files.
  job-doxygen:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    # Add a step to install Doxygen
    - name: Install Doxygen
      run: |
        choco install doxygen.portable -y
        set PATH="/c/tools/doxygen:$PATH"
    # Add a step to generate documentation using Doxygen
    - name: Generate Documentation
      #run: doxygen Doxyfile
      run: doxygen -g
#
  # Install build tools.
  buildtools:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print build tools versions (1/2)
        run: |
          gcc --version
          make -v
          mingw32-make -v
        
  # Build job: Make executable from source using Makefile.
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools and build
        run: |
          cd build-tools/strawberryperl/c/bin
          dir
          $env:PATH = "$pwd;$PATH"
          $env:PATH
          gcc --version
          make -v
          mingw32-make -v
          cd ../../../..
          make all
          make check
          make distcheck
  
  # Codecov job: Run CodeCov.
  codecov:
    if: ${{ always() }} # always run this job even if previous jobs failed.
    needs: build # run this job after "build" job has finished.
    runs-on: windows-latest
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
